"""Ajout table user + relation range

Revision ID: 1d40e8951fcd
Revises: 64e57ec945cc
Create Date: 2020-06-29 13:49:36.209630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d40e8951fcd'
down_revision = '64e57ec945cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('pokerrange', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pokerrange_timestamp'), 'pokerrange', ['timestamp'], unique=False)
    op.drop_index('ix_range_timestamp', table_name='pokerrange')
    op.create_foreign_key(None, 'pokerrange', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokerrange', type_='foreignkey')
    op.create_index('ix_range_timestamp', 'pokerrange', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_pokerrange_timestamp'), table_name='pokerrange')
    op.drop_column('pokerrange', 'user_id')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
