"""création table ranges

Revision ID: 64e57ec945cc
Revises: 
Create Date: 2020-05-23 22:23:17.841933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e57ec945cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phero', sa.String(length=10), nullable=True),
    sa.Column('pvillain', sa.String(length=10), nullable=True),
    sa.Column('num_range', sa.Integer(), nullable=True),
    sa.Column('range', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_range_timestamp'), 'range', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_range_timestamp'), table_name='range')
    op.drop_table('range')
    # ### end Alembic commands ###
